import fs from 'node:fs';
import path from 'node:path';
// import { fileURLToPath } from 'node:url';

/**
 * 生成侧边栏配置脚本
 * 遍历 docs 目录下的所有 Markdown 文件和文件夹，生成符合 VitePress 侧边栏配置格式的对象
 * 1. 先安装 npm install ts-node typescript --save-dev
 * 2. 然后运行 npx ts-node scripts/generate-sidebar.mts
 * 
 */

/**
 * 递归读取目录，生成侧边栏配置
 */
function generateSidebarItems(dir: string, basePath: string = ''): Array<{ text: string; link?: string; items?: any[] }> {
  const entries = fs.readdirSync(dir);
  const sidebar: Array<{ text: string; link?: string; items?: any[] }> = [];

  const stat = fs.statSync(dir);
  if (!stat.isDirectory()) {
    throw new Error(`Path is not a directory: ${dir}`);
  }
  // console.log(dir, entries);
  
  entries.forEach((entry) => {
    const fullPath = path.join(dir, entry);
    const stat = fs.statSync(fullPath);
    const relativePath = path.join(basePath, entry).replace(/\\/g, '/');

    if (stat.isDirectory()) {
      // 跳过resources目录
      if (entry === 'resources') {
        return;
      }

      const dirEntries = fs.readdirSync(fullPath);

      // console.log(fullPath, 'Directory entries:', dirEntries);
      let linker: { text: string; link?: string; items?: any[] }  = { text: '' };
      // 目录：作为一个侧边栏组
      linker.text = capitalizeFirstLetter(entry);
      if (dirEntries.includes('index.md')) {
        // 如果目录下有 index.md 文件，则将其作为目录的链接
        linker.link = `/${relativePath}/`;
      }
      
      // 目录：递归处理
      const children = generateSidebarItems(fullPath, relativePath);
      
      if (children.length > 0) {
        linker.items = children;
      }
      sidebar.push(linker);
    } else if (entry.endsWith('.md') && entry !== 'index.md' && entry !== '404.md') {
      // Markdown 文件
      const label = path.basename(entry, '.md');
      sidebar.push({
        text: capitalizeFirstLetter(decodeURIComponent(label)),
        link: `/${relativePath.replace('.md', '')}`,
      });
    }
  });

  return sidebar;
}


function generateSidebar(dir: string, basePath: string = ''): { text: string; link?: string; items?: any[] } {
  // console.log('enter', dir, basePath);

  const result: { text: string; link?: string; items?: any[] } = { text: '' };
  const entries = fs.readdirSync(dir);
  const sidebar: Array<{ text: string; link?: string; items?: any[] }> = [];

  const stat = fs.statSync(dir);
  if (!stat.isDirectory()) {
    throw new Error(`Path is not a directory: ${dir}`);
  }
  // console.log(11, dir, entries);
  
  result.text = capitalizeFirstLetter(path.basename(dir));
  if (entries.includes('index.md')) {
    // 如果目录下有 index.md 文件，则将其作为目录的链接
    result.link = '/' + basePath + '/';
  }


  entries.forEach((entry) => {
    const fullPath = path.join(dir, entry);
    const stat = fs.statSync(fullPath);
    const relativePath = path.join(basePath, entry).replace(/\\/g, '/');

    if (stat.isDirectory()) {
      // 跳过resources目录
      if (entry === 'resources') {
        return;
      }

      const dirEntries = fs.readdirSync(fullPath);

      // console.log(12, fullPath, 'Directory entries:', dirEntries);
      let linker: { text: string; link?: string; items?: any[] }  = { text: '' };
      // 目录：作为一个侧边栏组
      linker.text = capitalizeFirstLetter(entry);
      if (dirEntries.includes('index.md')) {
        // 如果目录下有 index.md 文件，则将其作为目录的链接
        linker.link = `/${relativePath}/`;
      }
      
      // 目录：递归处理
      const children = generateSidebarItems(fullPath, relativePath);
      
      if (children.length > 0) {
        linker.items = children;
      }
      sidebar.push(linker);
    } else if (entry.endsWith('.md') && entry !== 'index.md' && entry !== '404.md') {
      // Markdown 文件
      sidebar.push({
        text: capitalizeFirstLetter(decodeURIComponent(path.basename(entry, '.md'))),
        link: `/${relativePath.replace('.md', '')}`,
      });
    }
  });

  result.items = sidebar;
  return result;
}

/**
 * 首字母大写
 */
function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}


/**
 * Generating sidebar from D:\projects\ccgProjs\vue3\cg-vitepress\docs\src
 * to D:\projects\ccgProjs\vue3\cg-vitepress\docs\.vitepress\src\config\auto_sidebar.ts
 */
// 配置项
const DOCS_DIR = 'docs/src';
const OUTPUT_FILE = 'docs/.vitepress/src/config/auto_sidebar.ts';

function auto_generate() {
  // 执行生成
  try {
    // 确保 docs 目录存在
    if (!fs.existsSync(DOCS_DIR)) {
      throw new Error(`Docs directory does not exist: ${DOCS_DIR}`);
    }
    const sidebarConfig = generateSidebarItems(DOCS_DIR);

    const fileContent = `/**
  * This file is auto-generated by scripts/generate-sidebar.mts
  * DO NOT EDIT MANUALLY
  */
  export default ${JSON.stringify(sidebarConfig, null, 2)};
  `;

    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`✅ Generating sidebar successfully from ${DOCS_DIR} to ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('❌ Error generating sidebar:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

// 不使用全自动的，使用半自动的，可以自行定义顺序，支持index.md
// auto_generate()


export { generateSidebarItems, generateSidebar }