/**
 * This file is auto-generated by scripts/generate-sidebar.mts
 * DO NOT EDIT MANUALLY
 */
export default [
  {
    "text": "Aa",
    "items": [
      {
        "text": "A1",
        "link": "/aa/a1"
      },
      {
        "text": "A2",
        "link": "/aa/a2"
      }
    ]
  },
  {
    "text": "Api-examples",
    "link": "/api-examples"
  },
  {
    "text": "Bb",
    "items": [
      {
        "text": "B1",
        "link": "/bb/b1"
      },
      {
        "text": "B2",
        "link": "/bb/b2"
      },
      {
        "text": "Bc",
        "items": [
          {
            "text": "Bc1",
            "link": "/bb/bc/bc1"
          },
          {
            "text": "Bc2",
            "link": "/bb/bc/bc2"
          }
        ]
      }
    ]
  },
  {
    "text": "Markdown-examples",
    "link": "/markdown-examples"
  }
];
